server=1
wallet=1
disablewallet=0
rest=1
listen=1
regtest=1
printtoconsole=1
txindex=1
dnsseed=0
upnp=1
usecashaddr=0

rpcport=18332
port=18333
rpcuser=bitcoin
rpcpassword=bitcoin
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

bind=0.0.0.0
whitelist=0.0.0.0/0
connect=3.107.165.86:18333
connect=3.27.37.63:18333

excessiveblocksize=2000000000
maxblocksize=2000000000
maxmineblocksize=128000000
maxstackmemoryusageconsensus=200000000
